"""ajout du login

Revision ID: d0ec6a164a3d
Revises: 41d1a8559dc9
Create Date: 2022-04-09 15:28:57.483069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ec6a164a3d'
down_revision = '41d1a8559dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
